version: "3.5"
services:
    db:
        container_name: "db"
        image: postgres:latest
        env_file:
            - ./database.conf
        ports:
          - 5432:5432
        volumes:
            - db_volume:/var/lib/postgresql
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
    app:
        container_name: "py-postgres-if"
        image: py-postgres-if:7
        ports:
            - 8080:80
volumes:
    db_volume: